@host_http = http://localhost:880
@host_docker = http://localhost:8808

### Health Check (via Nginx HTTP)
GET {{host_http}}/health

---------------------------------------

### Health Check (Direct to Server - Docker)
GET {{host_docker}}/health

### Login
POST {{host_docker}}/api/v1/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "123"
}

### Register
POST {{host_docker}}/api/v1/register
Content-Type: application/json

{
  "full_name": "asdasdasdasd",
  "email": "admin@gmail.com",
  "password": "123"
}
